### PR TITLE
Using badgerdb for storage

### PR DESCRIPTION
**Pull request by brandonwestcott**
Adds in a working badgerdb storage

### CODE REVIEW

**Review by tobowers — APPROVED** [review]
this is also awesome... next step would be to see about changing the port here for testing... which I also think is now possible... though still not sure.

**Comment by tobowers** [comment]
you might have already seeen this, but just sharing knowledge on here that the go datastore for badger requires a higher version of badger than we use.

**Comment by tobowers** [comment]
and not master

**Comment by brandonwestcott** [comment]
Yeah i had to specify it to that newest revision of badger to get it to work

**Pull request merged**
